###################### Rabbitmqbeat Configuration Example #######################

# This file is an example configuration file highlighting only the most common
# options. The metricbeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#==========================  Modules configuration ============================
rabbitmqbeat.modules:

#------------------------------ RabbitMQ Module ------------------------------
- module: rabbitmq
  metricsets: ["nodes", "queues","overview", "connections" ]
  enabled: true
  period: 30s
  hosts: ["http://localhost:15672"]
  username: guest
  password: guest


